title: "Swetha Subramanian"
url: "https://swetha-subramanian6.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "default" 

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/
paginate: 5

# Author info
author:
  name: "Swetha Subramanian"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

# Navigation and layout
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      comments: false
      toc: true
      toc_sticky: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# Collections
collections:
  pages:
    output: true

# Social links
github_username: swetha-subramanian6
